# wrangler.toml
name = "buddha-jumps-over-thewall"  # 涓庝綘鐨刉orker鍚嶇О涓€鑷?compatibility_date = "2025-10-27"  # 涓庤繍琛屾椂鍏煎鏃ユ湡涓€鑷?
# 鍏ュ彛鏂囦欢锛堟贩娣哻ate.yml鐢熸垚鐨勬贩娣嗘枃浠讹級
main = "灏戝勾浣犵浉淇″厜鍚?

# KV瀛樺偍缁戝畾锛堜娇鐢ㄤ綘鐨凨V ID锛?[[kv_namespaces]]
binding = "C"  # 蹇呴』涓嶳EADME瑕佹眰鐨勫彉閲忓悕淇濇寔涓€鑷?id = "b70dd1ed392149e4926e81a1ed245e29"  # 浣犵殑KV鍛藉悕绌洪棿ID
